version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  secrets-env:
    lang: golang-middleware
    handler: ./secrets-env
    image: alexellis2/secrets-env:0.1.3
    environment:
      s3-access-key: AWS_ACCESS_KEY_ID
      s3-secret-key: AWS_SECRET_ACCESS_KEY
    secrets:
      - s3-access-key
      - s3-secret-key
